
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-doacoes
    environment:
      POSTGRES_DB: doacoes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - doacoes-network

volumes:
  postgres_data:

networks:
  doacoes-network:
    driver: bridge